In [5]:
import numpy as np

In [7]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [9]:
np.__version__

'1.26.4'

In [11]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [61]:
arr=np.array(my_list)

In [63]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr) #ndarray is n dimension array.

numpy.ndarray

In [9]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
np.arange()

TypeError: arange() requires stop to be specified.

In [70]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [72]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [73]:
np.arange(10,33,3)

array([10, 13, 16, 19, 22, 25, 28, 31])

In [74]:
np.arange(10,33,3,4)

TypeError: Cannot interpret '4' as a data type

In [129]:
np.arange(20,8) #first argument must be smaller than the 2nd argument

array([], dtype=int32)

In [130]:
np.arange(-10,33,3)

array([-10,  -7,  -4,  -1,   2,   5,   8,  11,  14,  17,  20,  23,  26,
        29,  32])

In [131]:
np.zeros(3)

array([0., 0., 0.])

In [132]:
np.zeros(3,dtype=int) #Hyper parameter

array([0, 0, 0])

In [133]:
h=np.zeros(5)

In [134]:
h

array([0., 0., 0., 0., 0.])

In [135]:
np.zeros((2,2)) #2d array

array([[0., 0.],
       [0., 0.]])

In [136]:
np.zeros((3,3),dtype=int) # 3*3 matrix 1st 3 is row and 2nd refer to column

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [137]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [138]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [139]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [140]:
rand(3,2)

NameError: name 'rand' is not defined

In [183]:
np.random.rand(2)

array([0.63368762, 0.39243893])

In [13]:
import numpy as np

In [14]:
np.random.rand(2)

array([0.73996114, 0.08067836])

In [15]:
np.random.rand(3)

array([0.77290658, 0.6338032 , 0.68697518])

In [16]:
np.random.rand(2,3)

array([[0.11595546, 0.18430846, 0.50902248],
       [0.66794378, 0.97941102, 0.49658277]])

In [17]:
np.random.randint(3)

1

In [18]:
np.random.randint(2,9)

8

In [19]:
np.random.randint(2,9,4)

array([4, 7, 6, 6])

In [20]:
np.random.randint(22,93,15)

array([79, 91, 49, 28, 51, 24, 64, 91, 63, 91, 83, 66, 32, 89, 39])

In [21]:
np.random.randint(10,40,(10,10))

array([[16, 23, 35, 14, 29, 11, 11, 34, 17, 26],
       [13, 29, 32, 15, 23, 21, 27, 30, 38, 16],
       [39, 10, 21, 13, 16, 19, 35, 20, 24, 18],
       [31, 14, 29, 16, 23, 10, 37, 38, 31, 32],
       [29, 10, 25, 13, 31, 13, 17, 29, 27, 36],
       [38, 33, 29, 39, 36, 16, 34, 31, 13, 33],
       [32, 37, 20, 12, 22, 27, 34, 24, 26, 30],
       [37, 15, 32, 23, 36, 11, 29, 28, 36, 17],
       [37, 30, 20, 19, 28, 28, 31, 35, 27, 26],
       [24, 29, 10, 29, 37, 33, 29, 19, 35, 22]])

In [22]:
r=np.random.randint(10,40,(10,10))
r

array([[25, 21, 38, 36, 28, 34, 22, 15, 25, 24],
       [12, 25, 31, 14, 22, 37, 15, 18, 27, 12],
       [15, 38, 31, 10, 38, 11, 35, 14, 16, 16],
       [34, 36, 15, 37, 13, 16, 36, 24, 31, 36],
       [10, 37, 37, 14, 21, 17, 28, 36, 29, 24],
       [10, 24, 36, 17, 16, 26, 28, 32, 21, 18],
       [36, 21, 12, 19, 18, 17, 26, 32, 27, 18],
       [33, 16, 25, 37, 31, 21, 20, 27, 11, 23],
       [20, 20, 16, 21, 15, 31, 30, 35, 22, 32],
       [32, 24, 19, 14, 13, 37, 20, 29, 14, 19]])

In [65]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(1,6)

In [ ]:
r

In [ ]:
b=np.random.randint(10,20,(5,4))

sLICING

In [ ]:
b

In [ ]:
b[:]

In [ ]:
b[1:4]

In [ ]:
b[-1:]

In [ ]:
b[:-1]

In [ ]:
b[2,3]

In [ ]:
from numpy import *

In [ ]:
arr

In [ ]:
arr.max()

In [ ]:
arr.min()

In [ ]:
arr

In [ ]:
arr.mean()

In [ ]:
from numpy import *
a=array([1,2,3,4,5])
median(a)

In [ ]:
arr

In [ ]:
arr.reshape(1,6)

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(3,2)

In [ ]:
arr.reshape(2,3,order='C')

In [ ]:
arr.reshape(6,1,order='F')

In [ ]:
arr.reshape(2,3,order='A')

In [67]:
mat=np.arange(0,100).reshape(10,10)

In [69]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
row=5
col=6

In [73]:
col

6

In [75]:
mat[row,col]

56

In [78]:
mat[4,5]

45

In [80]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [82]:
mat[4]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

mat[:,7]

In [85]:
mat[:7]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [87]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [89]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [91]:
mat[1,5]

15

In [93]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [95]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [97]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [99]:
mat[2:6,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [101]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [103]:
id(mat)

3245111823696

In [105]:
mat[mat<=61]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61])

In [107]:
mat[mat==50] 

array([50])

In [109]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])